#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2015-2018 StorPool Storage AD
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

PCI_SLOT_LIST=
PCI_MTU_LIST=
PCI_NUMVFS_LIST=
n=0
for dev in /sys/class/net/*/device; do
    . "$dev/uevent"
    if [ $DRIVER = "ixgbe" ]||[ $DRIVER = "i40e" ]; then
        . "$dev/driver/$PCI_SLOT_NAME"/net/*/uevent
        mac=$(<"$dev/driver/$PCI_SLOT_NAME/net/$INTERFACE/address")
        echo "#$PCI_SLOT_NAME $mac $INTERFACE $DRIVER "
        [ -n "$PCI_SLOT_LIST" ] && PCI_SLOT_LIST+=",$PCI_SLOT_NAME" || PCI_SLOT_LIST="$PCI_SLOT_NAME"
        [ -n "$PCI_MTU_LIST" ] && PCI_MTU_LIST+=",9000" || PCI_MTU_LIST="9000"
        [ -n "$PCI_NUMVFS_LIST" ] && PCI_NUMVFS_LIST+=",8" || PCI_NUMVFS_LIST="8"
        let n=n+1
    else
        echo "#$PCI_SLOT_NAME $DRIVER [skipped]" >&2
    fi
done

[ -n "$PCI_SLOT_LIST" ] || exit

echo ""PCI_SLOT_LIST=\"$PCI_SLOT_LIST\"
echo ""PCI_MTU_LIST=\"$PCI_MTU_LIST\"
echo ""PCI_NUMVFS_LIST=\"$PCI_NUMVFS_LIST\"

for ((i=0;i<$n;i++));do
    echo PCI${i}_VF_SPOOFCHK_LIST=\"off,off,off,off,off,off,off,off\"
done
